name: actions-rs-test
on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      notify_discord:
        description: notify discord message yes/no
        required: false
        default: 'no'

jobs:
  build-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      # - uses: Swatinem/rust-cache@v1

      - name: Cache cargo bin
        uses: actions/cache@v2
        with:
          path: |
            /usr/share/rust/.cargo/.crates.toml
            /usr/share/rust/.cargo/.crates2.json
            /usr/share/rust/.cargo/registry/index
            /usr/share/rust/.cargo/registry/cache
            /usr/share/rust/.cargo/git/db
            /usr/share/rust/.cargo/bin/
            ./target
          key: ${{ runner.os }}-cargo-bin-v1-${{ hashFiles('/usr/share/rust/.cargo/.crates.toml') }}-${{ hashFiles('/usr/share/rust/.cargo/.crates2.json') }}-${{ hashFiles('./Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-bin-v1-


      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - run: cargo install cargo2junit --version 0.1.6 

      - run: echo "echo no yes? msg=${{github.event.inputs.notify_discord}}-->actual action= ${{ ((github.event.inputs.notify_discord  == 'no' ) && 'no' || 'yes' ) !='no' }}"
        if: ${{  always() && ((github.event.inputs.notify_discord  == 'no' ) && 'no' || 'yes' ) != 'no' }}

      - name: success command 
        run: echo success
        id: success1

      - name: cargo build
        run: cargo build

      - name: cargo run
        run: cargo run

      - run: ls -la ~/.cargo/bin

      - run: ls -la ~/.cargo/bin

      - run: whereis cargo

      - run: whereis cargo2junit
      # - name: failure command 
      #   run: asdf
      #   id: failure1
      #   continue-on-error: true
        
      # - run: echo "failure or ${{steps.success1.outcome}} or ${{steps.failure1.outcome}} should be ${{ true ||steps.success1.outcome != 'success' || steps.failure1.outcome != 'success'}} and this echo should run."
      #   if: ${{ failure() || steps.success1.outcome != 'success' || steps.failure1.outcome != 'success' }}
 
