name: actions-rs-test
on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      notify_discord:
        description: notify discord message yes/no
        required: false
        default: 'no'

jobs:
  build-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Cache cargo bin
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-bin-${{ hashFiles('*/*') }}
          restore-keys: |
            ${{ runner.os }}-cargo-bin-

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v1

      - run: cargo install cargo2junit

      - run: echo "echo no yes? = ${{ ((github.event.inputs.notify_discord  == 'no' ) && 'no' || 'yes' ) !='no' }}"
        if: ${{  always() && ((github.event.inputs.notify_discord  == 'no' ) && 'no' || 'yes' ) != 'no' }}

      - name: success command 
        run: echo success
        id: success1

      - name: failure command 
        run: asdf
        id: failure1
        continue-on-error: true
        
      - run: echo "failure or ${{steps.success1.outcome}} or ${{steps.failure1.outcome}} should be ${{ true ||steps.success1.outcome != 'success' || steps.failure1.outcome != 'success'}} and this echo should run."
        if: ${{ failure() || steps.success1.outcome != 'success' || steps.failure1.outcome != 'success' }}
 
