name: actions-rs-test
on:
  workflow_dispatch:
jobs:
  build-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.cargo/bin/
          key: ${{ runner.os }}-cargo-bin-${{ hashFiles('*') }}
          restore-keys: |
            ${{ runner.os }}-cargo-bin-
            ${{ runner.os }}-cargo-
            ${{ runner.os }}-

      - run: cargo install cargo2junit