name: actions-rs-test
on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      notify_discord:
        description: notify discord message yes/no
        required: true
        default: 'no'

jobs:
  build-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Cache cargo bin
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-bin-${{ hashFiles('*/*') }}
          restore-keys: |
            ${{ runner.os }}-cargo-bin-

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v1

      - run: cargo install cargo2junit

      - run: echo "echo no yes? = ${{ ( ( github.event.inputs.notify_discord == '' || github.event.inputs.notify_discord  == 'no' )&& 'no' || 'yes' ) !='no' }}"
        if: ${{  always() && (( github.event.inputs.notify_discord == '' || github.event.inputs.notify_discord  == 'no' ) && 'no' || 'yes' ) != 'no' }}

      - run: echo "'false' 'false' 'true' should be 'true', get ${{false || false || true}}"
        if: ${{ success() && false && true }}