# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  webhooktest:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        id: cmd_id1
        run: echo ss
        
      - name: Run a one-line script
        id: cmd_id2
        run: echo ss

      # Runs a set of commands using the runners shell
      - name: CMD fail
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        if: ${{always() && (steps.cmd_id.outcome == 'failure')}}
        with:
          args: |
            > cmd failure 
            url: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
          
      - name: CMD success
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        if: ${{always()}}
        with:
          args: |
            >>> status: 
            "        "- ${{steps.cmd_id1.outcome && ':white_check_mark:' || ':x:'}} ${{steps.cmd_id1.outcome}}
             url: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}

